using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DeltaEngine.Platforms")]
[assembly: AssemblyDescription("Delta Engine Library Platforms")]
[assembly: AssemblyCompany("Delta Engine")]
[assembly: AssemblyCopyright("Copyright © Delta Engine 2014")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("d3899bdd-5e1b-4660-888b-58a98c6b2c02")]
[assembly: AssemblyVersion("1.1")]
[assembly: AssemblyFileVersion("1.1")]
[assembly: InternalsVisibleTo("DeltaEngine.Editor.OpenGL")]
[assembly: InternalsVisibleTo("DeltaEngine.Editor.OpenTK20")]
[assembly: InternalsVisibleTo("DeltaEngine.Editor.SharpDX")]
[assembly: InternalsVisibleTo("DeltaEngine.Platforms.Mocks")]
[assembly: InternalsVisibleTo("DeltaEngine.Platforms.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithGLFW2")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithGLFW3")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithES20")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithOpenTK11")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithOpenTK20")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithES11")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithSharpDX")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithSlimDX")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithXNA")]
[assembly: InternalsVisibleTo("DeltaEngine.TestWithMonoGame")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsGLFW2")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsGLFW3")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsES20")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsOpenTK11")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsOpenTK20")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsOpenGL")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsES11")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsSharpDX")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsSlimDX")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsXna")]
[assembly: InternalsVisibleTo("DeltaEngine.WindowsMonoGame")]
[assembly: InternalsVisibleTo("DeltaEngine.Input.Remote")]
[assembly: InternalsVisibleTo("DeltaEngine.Input.Remote.Tests")]
